# Generated by Django 5.2 on 2025-04-13 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tour', 'Tour'), ('perceuse', 'Perceuse')], max_length=50)),
                ('statut', models.CharField(choices=[('operationnel', '🟢 Opérationnel'), ('en_panne', '🔴 En panne')], max_length=20)),
                ('derniere_maintenance', models.DateField(blank=True, null=True)),
                ('frequence_jours', models.PositiveIntegerField(default=30)),
                ('emplacement', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('frequence', models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('yearly', 'Annuelle')], max_length=20)),
                ('prochaine_date', models.DateField()),
                ('statut', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('done', 'Terminée')], default='planned', max_length=20)),
                ('date_derniere_realisation', models.DateField(blank=True, null=True)),
                ('duree', models.FloatField(blank=True, help_text='Durée estimée ou réelle en heures', null=True)),
                ('cout', models.FloatField(blank=True, help_text='Coût réel de la maintenance', null=True)),
                ('on_time', models.BooleanField(default=True, help_text="Terminée à l'heure")),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenances',
            field=models.ManyToManyField(blank=True, related_name='machines', to='core.maintenancepreventive'),
        ),
        migrations.CreateModel(
            name='MesureCapteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('alerte', 'Alerte'), ('panne', 'Panne'), ('maintenance', 'Maintenance')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='PieceRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('quantite_stock', models.PositiveIntegerField()),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=8)),
                ('machines_compatibles', models.ManyToManyField(to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preventive', 'Préventive'), ('corrective', 'Corrective')], max_length=20)),
                ('date', models.DateField()),
                ('technicien', models.CharField(max_length=100)),
                ('duree', models.DurationField()),
                ('cout', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
                ('pieces_utilisees', models.ManyToManyField(blank=True, to='core.piecerechange')),
            ],
        ),
    ]
