# Generated by Django 5.2 on 2025-04-18 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_maintenancepreventive_machine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='cout',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='date',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='pieces_utilisees',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='type',
        ),
        migrations.AddField(
            model_name='intervention',
            name='date_intervention',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='etat_final',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='intervention',
            name='terminee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='core.machine'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
