# Generated by Django 5.2 on 2025-04-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_intervention_cout_remove_intervention_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_planifiee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='planifiee', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_intervention',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
