# Generated by Django 5.2 on 2025-04-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_intervention_date_planifiee_intervention_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='duree_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
