# Generated by Django 5.2 on 2025-04-24 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_intervention_duree_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reglementaire', models.BooleanField(default=False)),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('checklist', models.TextField(blank=True)),
                ('temps_maintenance_h', models.PositiveIntegerField(default=0)),
                ('temps_maintenance_m', models.PositiveIntegerField(default=0)),
                ('temps_arret_h', models.PositiveIntegerField(default=0)),
                ('temps_arret_m', models.PositiveIntegerField(default=0)),
                ('frequence', models.PositiveIntegerField()),
                ('unite', models.CharField(choices=[('jours', 'Jours'), ('semaines', 'Semaines'), ('mois', 'Mois'), ('annees', 'Années')], max_length=20)),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('assignes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.machine')),
            ],
        ),
    ]
