# Generated by Django 5.2 on 2025-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenancepreventive_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planmaintenance',
            old_name='date_prochaine',
            new_name='date_fin',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='assignes',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='temps_arret_h',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='temps_arret_m',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='temps_maintenance_h',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='temps_maintenance_m',
        ),
        migrations.RemoveField(
            model_name='planmaintenance',
            name='unite',
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='periodicite',
            field=models.CharField(default='ponctuelle', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planmaintenance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planmaintenance',
            name='frequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='planmaintenance',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
