# Generated by Django 5.2 on 2025-04-27 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_date_prochaine_planmaintenance_date_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planmaintenance',
            name='assignes',
            field=models.ManyToManyField(blank=True, related_name='plans_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='checklist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='labels',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='temps_arret_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='temps_maintenance_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='unite',
            field=models.CharField(choices=[('jours', 'Jours'), ('semaines', 'Semaines'), ('mois', 'Mois'), ('annees', 'Années')], default='jours', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planmaintenance',
            name='periodicite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
