# Generated by Django 5.2 on 2025-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_planmaintenance_assignes_planmaintenance_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenances',
            field=models.ManyToManyField(blank=True, related_name='machines', to='core.planmaintenance'),
        ),
        migrations.DeleteModel(
            name='MaintenancePreventive',
        ),
    ]
